---
abstract: 'a POE Component that implements check_nrpe functionality'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
  Test::POE::Server::TCP: 0.16
distribution_type: module
generated_by: 'Module::Install version 0.78'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-NRPE
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Carp: 0
  Net::SSLeay: 1.3
  POE: 0.38
  POE::Component::SSLify: 0.14
  Socket: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.12
