---
abstract: 'A POE Component that implements check_nrpe functionality'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.47
  Test::POE::Server::TCP: 0.16
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300024, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-NRPE
requires:
  Carp: 0
  Net::SSLeay: 1.3
  POE: 1.004
  POE::Component::SSLify: 0.15
  Socket: 0
  perl: 5.006
resources:
  homepage: https://github.com/bingos/poe-component-client-nrpe
  repository: https://github.com/bingos/poe-component-client-nrpe.git
version: 0.20
